name: OpenMW_Config CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    tags: ['*']

jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: DreamWeave-MP/StroggForge/.github/workflows/libGlobalBuild.yml@v9
    secrets: inherit
    with:
      crate_names: '["openmw_config"]'
      dependent_repo_names: '["DreamWeave-MP/S3lightfixes"]'
      generate_benchmarks: true
