name: Corprus Crucible Manufacturing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    tags: ['*']

jobs:
  build-app:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: DreamWeave-MP/StroggForge/.github/workflows/rustGlobalBuild.yml@v13
    secrets:
      VT_API_KEY: ${{ secrets.VT_API_KEY }}
    with:
      binary_names: '["merged_lands"]'
      publish_docs: false
      cargo_publish: false
